version: '2.1'

services:

  sleep-data-service:
    container_name: sleep-data-service
    build: ./api/sleep-data/
    volumes:
      - './api/sleep-data:/usr/src/app'
      - './api/sleep-data/package.json:/usr/src/package.json'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=changeme

  frontend:
    container_name: eight-sleep-viewer
    build: ./frontend/
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
    depends_on:
      sleep-data-service:
        condition: service_started
    links:
      - sleep-data-service

  swagger:
    container_name: swagger
    build: ./api/sleep-data/swagger/
    volumes:
      - './api/sleep-data/swagger:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3004:3004' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
    depends_on:
      sleep-data-service:
        condition: service_started
    links:
      - sleep-data-service